### ISSUE TITLE
Publish a version of this gem?

### ISSUE THREAD

**Issue by petergoldstein** [nfedyashev/retryable#38]
@nfedyashev Is there a recently  published version of this gem from this fork?  If not, would you be willing to publish one?

Thanks!

**Comment by nfedyashev** [comment]
The latest rubygem version(3.0.5) is the one that's recommended to be used at the moment.

There were some commits since that published version but they were affecting only the testing & documentation part of the gem - those are not going to be released as a new gem version release for the following reasons:

 * there weren't any API changes to actual existing users of the gem since 3.0.5
 * people have higher trust in a gem version that has ~8M downloads than one with little
 * I don't want to waste the time of existing users of this gem that they may need to dedicate to reading updated CHANGELOG(or reviewing the source code)
